--- # software installation
- name: my test playbook
  hosts: webservers
  user: ansible
  become: true
  connection: ssh






  tasks:
    - name: installing package into hosts
      yum: 
        name: docker
        state: installed
      

